controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.02
      goal_time: 1.0
      joint_1:
        trajectory: 0.15
        goal: 0.05
      joint_2:
        trajectory: 0.15
        goal: 0.05
      joint_3:
        trajectory: 0.15
        goal: 0.05
      joint_4:
        trajectory: 0.15
        goal: 0.05
      joint_5:
        trajectory: 0.15
        goal: 0.05
      joint_6:
        trajectory: 0.15
        goal: 0.05
